version: "3.7"
services:


networks:
  drinksale:
    driver: bridge  
  
  app:
    build:
      args:
        user: muniu
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: drinksale
    container_name: drinksale-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - drinksale